name: Read Version

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ci-cd-assignment
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          VER=$(cat version.py)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${IMAGE_NAME} .

      - name: Tag Docker image
        run: docker tag $IMAGE_NAME ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}

      - name: Push Docker image
        run: docker push ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}
