name: Docker Pull, Run, and Test

on:
  pull_request:
    branches:
      - main

jobs:
  pull-run-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull your_image_name

      - name: Run Docker container
        run: docker run --name your_container_name -d your_image_name

      - name: Wait for container to finish
        run: docker wait your_container_name

      - name: Get test score
        run: SCORE=$(docker logs your_container_name | tail -n 1) && echo "::set-output name=score::$SCORE"

      - name: Check test score
        run: |
          SCORE=$INPUT_SCORE
          if (( $(echo "$SCORE > 0.50" | bc -l) )); then
            echo "Test passed. Score is greater than 0.50"
            exit 0
          else
            echo "Test failed. Score is not greater than 0.50"
            exit 1
          fi
        shell: bash
        env:
          INPUT_SCORE: ${{ steps.get-test-score.outputs.score }}
