name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types: [completed]

env:
  IMAGE_NAME: ci-cd-assignment
  REGISTRY: docker.io
  VERSION: 1.1


jobs:
  pull-run-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull $REGISTRY/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$VERSION

      - name: Run Docker container
        run: docker run --name $IMAGE_NAME -d ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:${VERSION}

      - name: Wait for container to finish
        run: docker wait $IMAGE_NAME

      - name: Get test score
        run: SCORE=$(docker logs $IMAGE_NAME| tail -n 1) && echo "::set-output name=score::$SCORE"

      - name: Check test score
        run: |
          SCORE=$INPUT_SCORE
          echo $SCORE
          if (( $(echo "$SCORE > 0.50" | bc -l) )); then
            echo "Test passed. Score is greater than 0.50"
            exit 0
          else
            echo "Test failed. Score is not greater than 0.50"
            exit 1
          fi
        shell: bash
        env:
          INPUT_SCORE: ${{ steps.get-test-score.outputs.score }}
