name: Train

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        description: 'Docker container/image name'
        required: true
      REGISTRY:
        description: 'Registry name'
        required: true
      VERSION:
        description: 'docker image version'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $ {{ inputs.IMAGE_NAME }}.

      - name: Tag Docker image
        run: docker tag $IMAGE_NAME ${{ inputs.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.IMAGE_NAME }}:${{ inputs.VERSION }}

      - name: Push Docker image
        run: docker push ${{ inputs.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ inputs.IMAGE_NAME }}:${{ inputs.VERSION }}
